-- 请求订单表
CREATE TABLE `or_api_request_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `req_id` varchar(64) NOT NULL COMMENT '请求ID',
  `user_id` bigint NOT NULL COMMENT '用户标识',
  `api_key_id` bigint NOT NULL COMMENT '用户apikey',
  `client_ip` varchar(45) NOT NULL COMMENT '客户端IP',
  `req_path` varchar(128) NOT NULL DEFAULT '/v1/chat/completions' COMMENT 'API路径',
  `req_stream` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否流式(0否1是)',
  `model_id` bigint NOT NULL COMMENT '请求模型id',
  `model_name` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '请求模型名称',
  `model_type` varchar(20) DEFAULT NULL COMMENT '模型类型：chat,image,audio,video,embedding',
  `resp_model_name` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '实际路由模型名称',
  `resp_model_id` bigint DEFAULT NULL COMMENT '实际路由模型id',
  `resp_vendor_id` bigint DEFAULT NULL COMMENT '实际下游服务商id',
  `finish_reason` varchar(64) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '终止原因',
  `prompt_tokens` int DEFAULT 0 COMMENT '输入Token数',
  `completion_tokens` int DEFAULT 0 COMMENT '输出Token数',
  `total_tokens` int DEFAULT 0 COMMENT '总Token数',
  `system_fingerprint` varchar(64) DEFAULT NULL COMMENT '系统指纹',
  `status_code` smallint DEFAULT '200' COMMENT 'HTTP状态码',
  `error_message` text DEFAULT NULL COMMENT '错误信息',
  `latency_ms` int DEFAULT NULL COMMENT '请求延迟(毫秒)',
  `created_at` timestamp NOT NULL COMMENT '请求时间(UNIX时间戳转换)',
  `server_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '服务端接收时间',

  `order_amount` decimal(18,8) DEFAULT NULL COMMENT '订单金额（用户实付金额）',
  `vendor_order_no` varchar(100) DEFAULT NULL COMMENT '下游服务商订单号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_req_id` (`req_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_model_id` (`model_id`),
  KEY `idx_vendor` (`resp_vendor_id`),
  KEY `idx_vendor_order_no` (`vendor_order_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='API请求订单表';